package algos.cannibals;

public class MissionariesAndCannibalsState {

    public final int wm;
    public final int wc;
    public final int em;
    public final int ec;
    public final boolean isBoatOnWestBank;
    public final int MAX_NUM;

    public MissionariesAndCannibalsState(int missionaries, int cannibals, boolean isBoatOnWestBank, int maxNum) {
        this.MAX_NUM = maxNum;
        this.wc = cannibals;
        this.wm = missionaries;
        this.ec = this.MAX_NUM - cannibals;
        this.em = this.MAX_NUM - missionaries;
        this.isBoatOnWestBank = isBoatOnWestBank;
    }

    public boolean isLegal() {
        if (wm < wc && wm > 0) {
            return false;
        }
        if (em < ec && em > 0) {
            return false;
        }
        return true;
    }

    public boolean isGoalAcheived() {
        return isLegal() && em == MAX_NUM && ec == MAX_NUM;
    }

    @Override
    public String toString() {
        return String.format("On the West bank there are %d missionaries and %d cannibals.%nOn the East bank there are %d missionaries and %d cannibals.%nThe boat is on the %s bank.", wm, wc, em, ec, isBoatOnWestBank ? "West" : "East");
    }

    // auto-generated by Eclipse
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (isBoatOnWestBank ? 1231 : 1237);
        result = prime * result + ec;
        result = prime * result + em;
        result = prime * result + wc;
        result = prime * result + wm;
        return result;
    }

    // auto-generated by Eclipse
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        MissionariesAndCannibalsState other = (MissionariesAndCannibalsState) obj;
        if (isBoatOnWestBank != other.isBoatOnWestBank) {
            return false;
        }
        if (ec != other.ec) {
            return false;
        }
        if (em != other.em) {
            return false;
        }
        if (wc != other.wc) {
            return false;
        }
        if (wm != other.wm) {
            return false;
        }
        return true;
    }
}
